// Copyright (c) 2006-2008 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef CHROME_TEST_ACTIVEX_TEST_CONTROL_CHROME_TEST_CONTROL_CP_H__
#define CHROME_TEST_ACTIVEX_TEST_CONTROL_CHROME_TEST_CONTROL_CP_H__


template <class T>
class CProxy_IChromeTestControlEvents
    : public IConnectionPointImpl<T, &__uuidof(_IChromeTestControlEvents),
                                  CComDynamicUnkArray> {
 //Warning this class will  be regenerated by the wizard.
 public:
};

#endif // #ifndef CHROME_TEST_ACTIVEX_TEST_CONTROL_CHROME_TEST_CONTROL_CP_H__
