# Copyright (c) 2006-2008 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

Import('env')

env = env.Clone()


env.Prepend(
    CPPPATH = [
        '$CHROME_SRC_DIR',
    ],
    LIBS = [
        'googleurl',
        env['ICU_LIBS'],  # TODO(sgk):  '$ICU_LIBS' when scons is fixed
        'base',
    ],
)

input_files = [
    'test_chrome_plugin.cc',
]


if env['PLATFORM'] == 'win32':
  env.Prepend(
      LINKFLAGS = [
          '/INCREMENTAL',

          '/MANIFEST',
          '/DELAYLOAD:"dwmapi.dll"',
          '/DELAYLOAD:"uxtheme.dll"',
          '/MACHINE:X86',
          '/FIXED:No',

          '/safeseh',
          '/dynamicbase',
          '/ignore:4199',
          '/nxcompat',

          '/DEBUG',
      ],
      LIBS = [
          'winmm.lib',
      ],
  )

  input_files.extend([
      'test_chrome_plugin.def',
  ])

dll = env.ChromeSharedLibrary('test_chrome_plugin', input_files)

i = env.Install('$TARGET_ROOT', dll)
env.Alias('chrome', i)

