# Copyright (c) 2006-2008 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

Import('env_test')

env_test = env_test.Clone()


env_test.Prepend(
    CPPDEFINES = [
        'RELIABILITY_TEST',     # seems to be unused
        'UI_TEST',
        'UNIT_TEST',
    ],
    CPPPATH = [
        '$GTEST_DIR/include',
        '$GTEST_DIR',
        '$SKIA_DIR/include',
        '$SKIA_DIR/include/corecg',
        '$SKIA_DIR/platform',
        '#/..',
    ],
    LIBS = [
        'googleurl',
        'skia',
        'libpng',
        'gtest',
        'base_gfx',
        'icuuc',
        'common',
        'zlib',
        'browser',
        'browser_views',
        'base',
        'automation',
    ],
)

env_test.Prepend(
    LINKFLAGS = [
        '/INCREMENTAL',
        '/DEBUG',

        '/DELAYLOAD:"dwmapi.dll"',
        '/DELAYLOAD:"uxtheme.dll"',

        '/MACHINE:X86',
        '/FIXED:No',

        '/safeseh',
        '/dynamicbase',
        '/ignore:4199',
        '/nxcompat',
    ],
    LIBS = [
        'comsupp.lib',
        'oleacc.lib',
        'psapi.lib',
        'rpcrt4.lib',
        'winmm.lib',
    ],
)

input_files = [
    '$CHROME_DIR/test/perf/mem_usage$OBJSUFFIX',
    '$CHROME_DIR/test/ui/ui_test$OBJSUFFIX',
    '$CHROME_DIR/test/ui/ui_test_suite$OBJSUFFIX',
    '$CHROME_DIR/test/test_file_util$OBJSUFFIX',
    'page_load_test.cc',
    'run_all_unittests.cc',
]

exe = env_test.ChromeTestProgram('reliability_tests', input_files)
i = env_test.Install('$TARGET_ROOT', exe)

env_test.Alias('chrome', i)

