# Copyright (c) 2006-2008 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

Import('env')

env = env.Clone()

env.Prepend(
    CPPPATH = [
        '../../..',
    ],
    LIBS = [
      'googleurl',
      env['ICU_LIBS'],  # TODO(sgk):  '$ICU_LIBS' when scons is fixed
      'base',
      # We only need to link with net due to use precompiled_net.pch.
      'net',
    ],
)

env.Append(
    CCFLAGS = [
        '/TP',
    ],

    LINKFLAGS = [
        '/INCREMENTAL',
        '/MANIFEST',
        '/DELAYLOAD:"dwmapi.dll"',
        '/DELAYLOAD:"uxtheme.dll"',
        '/DEBUG',
        '/SUBSYSTEM:CONSOLE',
        '/MACHINE:X86',
        '/FIXED:No',
        '/safeseh',
        '/dynamicbase',
        '/ignore:4199',
        '/nxcompat',
    ],
)

input_files = [
    'tld_cleanup.cc',
]

exe_targets = env.ChromeProgram('tld_cleanup', input_files)
i = env.Install('$TARGET_ROOT', exe_targets)
env.Alias('net', i)

env.Install('$TARGET_ROOT', exe_targets)

