# Copyright (c) 2006-2008 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

Import('env')

env = env.Clone()

env.Prepend(
    CPPPATH = [
        '$NPAPI_DIR',
        '$CHROME_SRC_DIR',
    ],
    LIBS = [
        'activex_shim',
        'googleurl',
        env['ICU_LIBS'],  # TODO(sgk):  '$ICU_LIBS' when scons is fixed
        'base',
        'Urlmon',
    ],
)

env.Append(
    LINKFLAGS = [
        '/INCREMENTAL',

        '/MANIFEST',
        '/DELAYLOAD:"dwmapi.dll"',
        '/DELAYLOAD:"uxtheme.dll"',
        '/MACHINE:X86',
        '/FIXED:No',

        '/safeseh',
        '/dynamicbase',
        '/ignore:4199',
        '/nxcompat',

        '/DEBUG',
    ],
)

input_files = [
    'activex_shim_dll.cc',
    'activex_shim_dll.def',
]

dll = env.ChromeSharedLibrary('npaxshim', input_files)

i = env.Install('$TARGET_ROOT', dll)
env.Alias('webkit', i)

env.ChromeMSVSProject('$WEBKIT_DIR/activex_shim_dll/activex_shim_dll.vcproj',
                dependencies = [
                    '$BASE_DIR/build/base.vcproj',
                    '$WEBKIT_DIR/activex_shim/activex_shim.vcproj',
                ],
                guid='{494E414B-1655-48CE-996D-6413ECFB7829}')
