# Copyright (c) 2006-2008 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

Import('env')

env = env.Clone()

env.Prepend(
    CPPPATH = [
        #'../../..',
        #'$GTEST_DIR/include',
        '$SKIA_DIR/include',
        '$SKIA_DIR/include/corecg',
        '$SKIA_DIR/platform',
        '#/..',
    ],
)

input_files = [
    'autocomplete_edit_proxy.cc',
    'automation_handle_tracker.cc',
    'automation_proxy.cc',
    'browser_proxy.cc',
    'constrained_window_proxy.cc',
    'tab_proxy.cc',
    'window_proxy.cc',
]

lib = env.ChromeStaticLibrary('automation', input_files)

i = env.Install('$TARGET_ROOT', lib)
env.Alias('chrome', i)

