# Copyright (c) 2006-2008 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

Import('env')

env = env.Clone()


env.Prepend(
    CPPPATH = [
        '$CHROME_DIR/app/resources',
        '/chrome/tools/build/win',
        '$CHROME_SRC_DIR',
    ],
    CPPDEFINES = [
        'U_STATIC_IMPLEMENTATION',
    ],
)

if env['PLATFORM'] == 'win32':
  env.Prepend(
      CCGLAGS = [
          '/TP',
      ],
  )

env.Append(
    CPPPATH = [
        'third_party/wtl/include',
        '$ICU38_DIR/public/common',
        '$ICU38_DIR/public/i18n',
        '$NPAPI_DIR',
        '$SKIA_DIR/include',
        '$SKIA_DIR/include/corecg',
        '$SKIA_DIR/platform',
    ],
)

input_files = []

# TODO(port): Port to Mac.
if env['PLATFORM'] in ('posix', 'win32'):
  input_files.extend([
      'about_handler.cc',
      'net/render_dns_queue.cc',
      'visitedlink_slave.cc',
  ])

# TODO(port): Port these.
if env['PLATFORM'] == 'win32':
  input_files.extend([
      'automation/dom_automation_controller.cc',
      'chrome_plugin_host.cc',
      'debug_message_handler.cc',
      'dom_ui_bindings.cc',
      'external_js_object.cc',
      'external_host_bindings.cc',
      'localized_error.cc',
      'net/render_dns_master.cc',
      'plugin_channel_host.cc',
      'render_process.cc',
      'render_thread.cc',
      'render_view.cc',
      'render_widget.cc',
      'renderer_glue.cc',
      'renderer_main.cc',
      'webplugin_delegate_proxy.cc',
  ])

# TODO(port): Enable for Mac.
if env['PLATFORM'] in ('posix', 'win32'):
  env.ChromeStaticLibrary('renderer', input_files)
