#!/bin/sh
#
# Copyright (c) 2009 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

PROGDIR=$(dirname $(readlink -f $0))
export LD_LIBRARY_PATH=$PROGDIR:$LD_LIBRARY_PATH
exec "$PROGDIR/@@PROGNAME@@" "$@"
