// Copyright (c) 2008 The Chromium Authors. All rights reserved.  Use of this
// source code is governed by a BSD-style license that can be found in the
// LICENSE file.

/* if ENABLE(DATABASE), there should be a databaseTableNames method. */

module core {
    interface InspectorController { 
        void addSourceToFrame(in unsigned long identifier, in Node frame);
        Node getResourceDocumentNode(in unsigned long identifier);
        void highlightDOMNode(in Node node);
        void hideDOMNodeHighlight();
        void loaded();
        [v8implname=close] void windowUnloading();
        void attach();
        void detach();
        void search(in Node node, in DOMString query);
        DOMWindow inspectedWindow();
        DOMString platform();
        DOMString localizedStringsURL();

        /* TODO(ojan): add these. These are in trunk webkit.
        #if ENABLE(DATABASE)
        { "databaseTableNames", databaseTableNames, kJSPropertyAttributeNone },
        #endif
        { "moveByUnrestricted", moveByUnrestricted, kJSPropertyAttributeNone },
        { "wrapCallback", wrapCallback, kJSPropertyAttributeNone },
        { "startDebuggingAndReloadInspectedPage", WebCore::startDebuggingAndReloadInspectedPage, kJSPropertyAttributeNone },
        { "stopDebugging", WebCore::stopDebugging, kJSPropertyAttributeNone },
        { "debuggerAttached", WebCore::debuggerAttached, kJSPropertyAttributeNone },
        */
    };
}
