/*
 * Copyright 2009, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/**
 * This file was auto-generated by a SketchUp ruby script. Include this in your
 * game and everything else will load right in.
 *
 * WARNING: This file will be overwritten when you publish a new level from
 * SketchUp, so if you wan to manually modify it, you've been warned. :)
 */
document.write('<script type="text/javascript" src="actors/actor.js"></script>');
document.write('<script type="text/javascript" src="actors/arrow.js"></script>');
document.write('<script type="text/javascript" src="actors/avatar.js"></script>');
document.write('<script type="text/javascript" src="actors/coin.js"></script>');
document.write('<script type="text/javascript" src="actors/horizontalpad.js"></script>');
document.write('<script type="text/javascript" src="actors/mover.js"></script>');
document.write('<script type="text/javascript" src="actors/spikem.js"></script>');
document.write('<script type="text/javascript" src="actors/verticalpad.js"></script>');

document.write('<script type="text/javascript" src="levels/all_actors.js"></script>');
document.write('<script type="text/javascript" src="levels/map1.js"></script>');
