# Copyright (c) 2006-2008 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

Import('env')

env = env.Clone()


env.Prepend(
    CPPPATH = [
        '#/..',
    ],
    CPPDEFINES = [
        'LIBXML_STATIC',
        'U_STATIC_IMPLEMENTATION',
        'PNG_USER_CONFIG',
        'CHROME_PNG_WRITE_SUPPORT',
    ],
    CCFLAGS = [
        '/TP',
    ],
)

env.Append(
    CPPPATH = [
        '$CHROME_DIR/third_party/wtl/include',
        '$NPAPI_DIR',
        '$LIBXML_DIR/include',
        '$ICU38_DIR/public/common',
        '$ICU38_DIR/public/i18n',
        '$CHROME_DIR/app',
        '$ZLIB_DIR',
        '$SKIA_DIR/include',
        '$SKIA_DIR/include/corecg',
        '$SKIA_DIR/platform',
        '$LIBPNG_DIR',
        '$BREAKPAD_DIR/src',
    ],
)

input_files = [
    'debugger_contents.cc',
    'debugger_io_socket.cc',
    'debugger_node.cc',
    'debugger_shell.cc',
    'debugger_view.cc',
    'debugger_window.cc',
    'debugger_wrapper.cc',
]

env.ChromeStaticLibrary('debugger', input_files)

