# Copyright (c) 2006-2008 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

Import('env')

# TODO(port):
if env.Bit('windows'):
  env.TypeLibrary('google_update_idl')

env.ChromeMSVSProject('$GOOGLE_UPDATE_DIR/ondemand_updates.vcproj',
                guid='{4052059A-D72B-4183-B5C2-9D1B099E9E35}')
