# Copyright (c) 2006-2008 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

Import('env')

input_files = ChromeFileList([
    'google_update_idl.idl',
])

# TODO(port):
if env.Bit('windows'):
  # TODO(sgk):  get from the input_files list.
  env.TypeLibrary('google_update_idl')

p = env.ChromeMSVSProject('ondemand_updates.vcproj',
                          dest=('$CHROME_SRC_DIR/google_update/' +
                                    'ondemand_updates.vcproj'),
                          guid='{4052059A-D72B-4183-B5C2-9D1B099E9E35}',
                          keyword='Win32Proj',
                          # TODO(sgk):  when we can intuit the hierarchy
                          # from the built targets.
                          #buildtargets=TODO,
                          files=input_files,
                          relative_path_prefix='./',
                          tools=[
                              'VCPreBuildEventTool',
                              'VCCustomBuildTool',
                              'VCMIDLTool',
                              'VCPostBuildEventTool',
                          ],
                          ConfigurationType='10')

p.AddConfig('Debug|Win32',
            InheritedPropertySheets=[
                '$(SolutionDir)../build/debug.vsprops',
            ])

p.AddConfig('Release|Win32',
            InheritedPropertySheets=[
                '$(SolutionDir)../build/release.vsprops',
            ])
