// Copyright (c) 2008 The Chromium Authors. All rights reserved.  Use of this
// source code is governed by a BSD-style license that can be found in the
// LICENSE file.

module html {

    // This interface is used for undetectable HTMLCollections.
    // An undetectable HTMLCollection behaves like an HTMLCollection
    // when used, but the 'typeof' operator returns undefined and
    // ToBoolean returns false.
    interface UndetectableHTMLCollection : HTMLCollection {
    };

}
