# Copyright 2008, Google Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#    * Redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above
# copyright notice, this list of conditions and the following disclaimer
# in the documentation and/or other materials provided with the
# distribution.
#    * Neither the name of Google Inc. nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Import('env', 'env_res')

env = env.Clone()
env_res = env_res.Clone()

input_files = [
    'npapi_constants.cc',
    'npapi_test.cc',
    env_res.RES('npapi_test.rc'),
    'plugin_arguments_test.cc',
    'plugin_client.cc',
    'plugin_delete_plugin_in_stream_test.cc',
    'plugin_execute_script_delete_test.cc',
    'plugin_get_javascript_url_test.cc',
    'plugin_geturl_test.cc',
    'plugin_new_fails_test.cc',
    'plugin_npobject_lifetime_test.cc',
    'plugin_npobject_proxy_test.cc',
    'plugin_test.cc',
    'plugin_window_size_test.cc',
    'npapi_test.def',

    '$BASE_DIR/base.lib',
]

env.Append(
    CCFLAGS = [
        '/TP',
        '/wd4800',
    ],

    LIBS = [
        'comctl32.lib',
        'shlwapi.lib',
        'rpcrt4.lib',
        'winmm.lib',
        'wininet.lib',
        'version.lib',
        'msimg32.lib',
        'ws2_32.lib',
        'usp10.lib',
        'psapi.lib',
        'kernel32.lib',
        'user32.lib',
        'gdi32.lib',
        'winspool.lib',
        'comdlg32.lib',
        'advapi32.lib',
        'shell32.lib',
        'ole32.lib',
        'oleaut32.lib',
        'uuid.lib',
        'odbc32.lib',
        'odbccp32.lib',

        'delayimp.lib',
    ],

    LINKFLAGS = [
        '/DELAYLOAD:"dwmapi.dll"',
        '/DELAYLOAD:"uxtheme.dll"',
        '/FIXED:No',
        '/SUBSYSTEM:CONSOLE',
        '/MACHINE:X86',
        '/safeseh',
        '/dynamicbase',
        '/ignore:4199',
        '/nxcompat',
    ],
)

dll = env.SharedLibrary(['npapi_test_plugin',
                         'npapi_test_plugin.ilk',
                         'npapi_test_plugin.pdb'],
                         input_files)

i = env.Install('$TARGET_ROOT', dll)
env.Alias('webkit', i)
