# Copyright (c) 2006-2008 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

Import('env', 'env_res')

env = env.Clone()
env_res = env_res.Clone()

input_files = [
    'npapi_constants.cc',
    'npapi_test.cc',
    env_res.RES('npapi_test.rc'),
    'plugin_arguments_test.cc',
    'plugin_client.cc',
    'plugin_delete_plugin_in_stream_test.cc',
    'plugin_execute_script_delete_test.cc',
    'plugin_get_javascript_url_test.cc',
    'plugin_geturl_test.cc',
    'plugin_new_fails_test.cc',
    'plugin_npobject_lifetime_test.cc',
    'plugin_npobject_proxy_test.cc',
    'plugin_test.cc',
    'plugin_window_size_test.cc',
    'npapi_test.def',
]

env.Append(
    LIBS = [
         'base',
    ],
)

env.Append(
    CCFLAGS = [
        '/TP',
        '/wd4800',
    ],

    LIBS = [
        'comctl32.lib',
        'rpcrt4.lib',
        'shlwapi.lib',
        'winmm.lib',
    ],

    LINKFLAGS = [
        '/INCREMENTAL',
        '/DELAYLOAD:"dwmapi.dll"',
        '/DELAYLOAD:"uxtheme.dll"',
        '/FIXED:No',
        '/SUBSYSTEM:CONSOLE',
        '/MACHINE:X86',
        '/safeseh',
        '/dynamicbase',
        '/ignore:4199',
        '/nxcompat',
    ],
)

dll = env.ChromeSharedLibrary(['npapi_test_plugin',
                         'npapi_test_plugin.lib',
                         'npapi_test_plugin.ilk',
                         'npapi_test_plugin.pdb'],
                         input_files)

# TODO(sgk):  goes away once ChromeSharedLibrary does this for us.
env.Install('$LIBS_DIR', dll[1])

i = env.Install('$TARGET_ROOT', dll)
env.Alias('webkit', i)

