# Copyright (c) 2006-2008 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

Import('env')

env = env.Clone()


env.Prepend(
    CPPPATH = [
        '#/..',
    ],
)

env.Prepend(
    LINKFLAGS = [
        '/INCREMENTAL',

        '/MANIFEST',
        '/DELAYLOAD:"dwmapi.dll"',
        '/DELAYLOAD:"uxtheme.dll"',
        '/MACHINE:X86',
        '/FIXED:No',

        '/safeseh',
        '/dynamicbase',
        '/ignore:4199',
        '/nxcompat',

        '/DEBUG',
    ],
    LIBS = [
        'DelayImp.lib',
    ],
)

input_files = [
    'ipc_security_tests.cc',
    'security_tests.cc',
    '$SANDBOX_DIR/tests/validation_tests/commands${OBJSUFFIX}',
]

dll = env.ChromeSharedLibrary(['security_tests',
                               'security_tests.lib',
                               'security_tests.ilk',
                               'security_tests.pdb'],
                              input_files)

# TODO(sgk):  can go away once ChromeSharedLibrary() handles this.
env.Install('$LIBS_DIR', dll[1])

i = env.Install('$TARGET_ROOT', dll)
env.Alias('chrome', i)

