# Copyright (c) 2006-2008 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

Import('env')

env.Install('$TARGET_ROOT',
            ['binaries/rlz.dll',
             'binaries/rlz_dll.pdb'])

