/*
 * Copyright 2009, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */


// This file contains the IDL declaration of the CursorType enumeration.

namespace o3d {

[include="core/cross/cursor.h"]
namespace Cursor {

%[
  \var CursorType
  \li DEFAULT
  \li NONE
  \li CROSSHAIR
  \li POINTER
  \li E_RESIZE
  \li NE_RESIZE
  \li NW_RESIZE
  \li N_RESIZE
  \li SE_RESIZE
  \li SW_RESIZE
  \li S_RESIZE
  \li W_RESIZE
  \li MOVE
  \li TEXT
  \li WAIT
  \li PROGRESS
  \li HELP
%]
enum CursorType {
  DEFAULT,
  NONE,
  CROSSHAIR,
  POINTER,
  E_RESIZE,
  NE_RESIZE,
  NW_RESIZE,
  N_RESIZE,
  SE_RESIZE,
  SW_RESIZE,
  S_RESIZE,
  W_RESIZE,
  MOVE,
  TEXT,
  WAIT,
  PROGRESS,
  HELP
};

}  // namespace Cursor

}  // namespace o3d
