/*
 * Copyright 2009, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

namespace o3d {

%[
  A RenderSurfaceBase is the base for RenderSurface and
  RenderDepthStencilSurface.
%]
[nocpp, include="core/cross/render_surface.h"] class RenderSurfaceBase
    : ParamObject {
  %[
    The width of the surface, in pixels.
  %]
  [field_access=private, getter] int width;

  %[
    The height of the surface, in pixels.
  %]
  [field_access=private, getter] int height;

};  // RenderSurfaceBaes


%[
  A RenderSurface encapsulates the notion of a renderable surface.
  When used in conjunction with a RenderSurfaceSet node in the render graph,
  the API allows for rendering of primitives to the given surface.
  RenderSurface objects are not constructable through the Pack API, they may
  only be accessed through the texture getRenderSurface(...) interfaces.
%]
[nocpp, include="core/cross/render_surface.h"] class RenderSurface
    : RenderSurfaceBase {
  %[
    The texture in which this surface is contained.
  %]
  [field_access=private, getter] Texture? texture;
};  // RenderSurface

%[
  A Param which stores a RenderSurface.
%]
[nocpp, include="core/cross/render_surface.h"] class ParamRenderSurface : Param
{%[
    The RenderSurface stored by the Param.
  %]
  [getter, setter] RenderSurface? value_;
};

%[
  A RenderDepthStencilSurface represents a depth stencil render surface.
%]
[nocpp, include="core/cross/render_surface.h"]
class RenderDepthStencilSurface
    : RenderSurfaceBase {
};  // RenderDepthStencilSurface

%[
  A Param which stores a RenderDepthStencilSurface.
%]
[nocpp, include="core/cross/render_surface.h"]
class ParamRenderDepthStencilSurface : Param
{%[
    The RenderDepthStencilSurface stored by the Param.
  %]
  [getter, setter] RenderDepthStencilSurface? value_;
};


}  // namespace o3d
