// Copyright (c) 2008 The Chromium Authors. All rights reserved.  Use of this
// source code is governed by a BSD-style license that can be found in the
// LICENSE file.

module events {

#if defined(V8_BINDING)
    interface EventTargetNode : Node, EventTarget {
        attribute [DontEnum, Custom=ElementEventHandler] DOMString onabort;
        attribute [DontEnum, Custom=ElementEventHandler] DOMString onbeforecopy;
        attribute [DontEnum, Custom=ElementEventHandler] DOMString onbeforecut;
        attribute [DontEnum, Custom=ElementEventHandler] DOMString onbeforepaste;
        attribute [DontEnum, Custom=ElementEventHandler] DOMString onblur;
        attribute [DontEnum, Custom=ElementEventHandler] DOMString onchange;
        attribute [DontEnum, Custom=ElementEventHandler] DOMString onclick;
        attribute [DontEnum, Custom=ElementEventHandler] DOMString oncontextmenu;
        attribute [DontEnum, Custom=ElementEventHandler] DOMString oncopy;
        attribute [DontEnum, Custom=ElementEventHandler] DOMString oncut;
        attribute [DontEnum, Custom=ElementEventHandler] DOMString ondblclick;
        attribute [DontEnum, Custom=ElementEventHandler] DOMString ondrag;
        attribute [DontEnum, Custom=ElementEventHandler] DOMString ondragend;
        attribute [DontEnum, Custom=ElementEventHandler] DOMString ondragenter;
        attribute [DontEnum, Custom=ElementEventHandler] DOMString ondragleave;
        attribute [DontEnum, Custom=ElementEventHandler] DOMString ondragover;
        attribute [DontEnum, Custom=ElementEventHandler] DOMString ondragstart;
        attribute [DontEnum, Custom=ElementEventHandler] DOMString ondrop;
        attribute [DontEnum, Custom=ElementEventHandler] DOMString onerror;
        attribute [DontEnum, Custom=ElementEventHandler] DOMString onfocus;
        attribute [DontEnum, Custom=ElementEventHandler] DOMString oninput;
        attribute [DontEnum, Custom=ElementEventHandler] DOMString onkeydown;
        attribute [DontEnum, Custom=ElementEventHandler] DOMString onkeypress;
        attribute [DontEnum, Custom=ElementEventHandler] DOMString onkeyup;
        attribute [DontEnum, Custom=ElementEventHandler] DOMString onload;
        attribute [DontEnum, Custom=ElementEventHandler] DOMString onmousedown;
        attribute [DontEnum, Custom=ElementEventHandler] DOMString onmousemove;
        attribute [DontEnum, Custom=ElementEventHandler] DOMString onmouseout;
        attribute [DontEnum, Custom=ElementEventHandler] DOMString onmouseover;
        attribute [DontEnum, Custom=ElementEventHandler] DOMString onmouseup;
        attribute [DontEnum, Custom=ElementEventHandler] DOMString onmousewheel;
        attribute [DontEnum, Custom=ElementEventHandler] DOMString onoverflowchanged;
        attribute [DontEnum, Custom=ElementEventHandler] DOMString onbeforeunload;
        attribute [DontEnum, Custom=ElementEventHandler] DOMString onpaste;
        attribute [DontEnum, Custom=ElementEventHandler] DOMString onreadystatechange;
        attribute [DontEnum, Custom=ElementEventHandler] DOMString onreset;
        attribute [DontEnum, Custom=ElementEventHandler] DOMString onresize;
        attribute [DontEnum, Custom=ElementEventHandler] DOMString onscroll;
        attribute [DontEnum, Custom=ElementEventHandler] DOMString onsearch;
        attribute [DontEnum, Custom=ElementEventHandler] DOMString onselect;
        attribute [DontEnum, Custom=ElementEventHandler] DOMString onselectstart;
        attribute [DontEnum, Custom=ElementEventHandler] DOMString onsubmit;
        attribute [DontEnum, Custom=ElementEventHandler] DOMString ontextInput;
        attribute [DontEnum, Custom=ElementEventHandler] DOMString onunload;
        attribute [DontEnum, Custom=ElementEventHandler] DOMString onzoom;
    };
#endif

}
