// Copyright (c) 2008 The Chromium Authors. All rights reserved.  Use of this
// source code is governed by a BSD-style license that can be found in the
// LICENSE file.

module core {
  interface [CheckDomainSecurity] Location {
    attribute DOMString hash;
    attribute DOMString host;
    attribute DOMString hostname;
    attribute [DoNotCheckDomainSecurityOnSet] DOMString href;
    attribute DOMString pathname;
    attribute DOMString port;
    attribute DOMString protocol;
    attribute DOMString search;

    [DoNotCheckDomainSecurity] void reload(in boolean forceget);
    [DoNotCheckDomainSecurity] void replace(in DOMString url);
    [DoNotCheckDomainSecurity] void assign(in DOMString url);

    [DontEnum] DOMString toString();
  };
}
