// Copyright (c) 2008 The Chromium Authors. All rights reserved.  Use of this
// source code is governed by a BSD-style license that can be found in the
// LICENSE file.

module core {
  interface [CheckDomainSecurity] Location {
    attribute DOMString hash;
    attribute DOMString host;
    attribute DOMString hostname;
    attribute [DoNotCheckDomainSecurityOnSet, v8DisallowShadowing] DOMString href;
    attribute DOMString pathname;
    attribute DOMString port;
    attribute DOMString protocol;
    attribute DOMString search;

    // For security reasons, these functions are on the instance
    // instead of on the prototype object to insure that they cannot
    // be overwritten.
    [DoNotCheckDomainSecurity, v8OnInstance] void reload(in boolean forceget);
    [DoNotCheckDomainSecurity, v8OnInstance] void replace(in DOMString url);
    [DoNotCheckDomainSecurity, v8OnInstance] void assign(in DOMString url);
    [ReadOnly, DontEnum, v8OnInstance] DOMString toString();
    [Custom, ReadOnly, DontEnum, v8OnInstance] DOMObject valueOf();
  };
}
