# Copyright (c) 2006-2008 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

Import('env')

env = env.Clone()

env.Prepend(
    CPPPATH = [
        '$NPAPI_DIR',
        '$CHROME_SRC_DIR',
    ],
)

env.Append(
    CPPDEFINES = [
        'TRACK_INTERFACE',
    ],
    CCFLAGS = [
        '/TP',

        '/WX',
        '/Wp64',
    ],
    LIBS = [
        'Urlmon',
    ],
)

input_files = [
    'activex_plugin.cc',
    'activex_shared.cc',
    'activex_util.cc',
    'dispatch_object.cc',
    'npn_scripting.cc',
    'npp_impl.cc',
    'web_activex_container.cc',
    'web_activex_site.cc',
]

env.ChromeLibrary('activex_shim', input_files)

env.ChromeMSVSProject('$WEBKIT_DIR/activex_shim/activex_shim.vcproj',
                dependencies = [
                    '$BASE_DIR/build/base.vcproj',
                    '$ICU38_DIR/build/icu.vcproj',
                    '$GOOGLEURL_DIR/build/googleurl.vcproj',
                ],
                guid='{F4F4BCAA-EA59-445C-A119-3E6C29647A51}')
