# Copyright (c) 2006-2008 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

Import('env')

env = env.Clone()

if env['PLATFORM'] == 'win32':
  env.Append(
    CCFLAGS = [
      '/TP',

      '/WX',

      '/wd4800',
    ],
  )

input_files = [
  'alt_404_page_resource_fetcher.cc',
  'alt_error_page_resource_fetcher.cc',
  'autocomplete_input_listener.cc',
  'cache_manager.cc',
  'chrome_client_impl.cc',
  'context_menu_client_impl.cc',
  'cpp_binding_example.cc',
  'cpp_bound_class.cc',
  'cpp_variant.cc',
  'debugger.cc',
  'dom_operations.cc',
  'editor_client_impl.cc',
  'entity_map.cc',
  'event_conversion.cc',
  'feed_preview.cc',
  'glue_util.cc',
  'glue_serialize.cc',
  'image_decoder.cc',
  'image_resource_fetcher.cc',
  'inspector_client_impl.cc',
  'localized_strings.cc',
  'npruntime_util.cc',
  'password_autocomplete_listener.cc',
  'password_form_dom_manager.cc',
  'resource_fetcher.cc',
  'searchable_form_data.cc',
  'simple_clipboard_impl.cc',
  'stacking_order_iterator.cc',
  'webcursor.cc',
  'webdatasource_impl.cc',
  'webdocumentloader_impl.cc',
  'weberror_impl.cc',
  'webkit_glue.cc',
  'webtextinput_impl.cc',
  'weburlrequest_impl.cc',
]

if env['PLATFORM'] == 'win32':
  # TODO(port): These extra files aren't win32-specific, they've just not been
  # tested on other platforms yet.
  input_files.append([
    '$PENDING_DIR/AccessibleBase.cpp',
    '$PENDING_DIR/AccessibleDocument.cpp',
    'dom_serializer.cc',
    'dragclient_impl.cc',
    'glue_accessibility.cc',
    'multipart_response_delegate.cc',
    'plugins/mozilla_extensions.cc',
    'plugins/plugin_host.cc',
    'plugins/plugin_instance.cc',
    'plugins/plugin_lib.cc',
    'plugins/plugin_list.cc',
    'plugins/plugin_stream.cc',
    'plugins/plugin_stream_url.cc',
    'plugins/plugin_string_stream.cc',
    'plugins/webplugin_delegate_impl.cc',
    'resource_handle_win.cc',
    'webdropdata.cc',
    'webframe_impl.cc',
    'webframeloaderclient_impl.cc',
    'webhistoryitem_impl.cc',
    'webinputevent_win.cc',
    'webplugin_impl.cc',
    'webview_impl.cc',
    'webwidget_impl.cc',
  ])

env.ChromeStaticLibrary('glue', input_files)
