# Copyright (c) 2006-2008 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

Import('env')

env = env.Clone()

env.Append(
    CPPPATH = [
        '$WEBKIT_DIR/build/WebCore',
    ],
    LIBS = [
        'port',
        'renderer',
        'V8Bindings',
        'WebCore',
        'WTF',
    ],
)

if env.Bit('windows'):
  env.Append(
      CCFLAGS = [
          '/TP',

          '/WX',

          '/wd4800',
      ],
  )

input_files = [
  'alt_404_page_resource_fetcher.cc',
  'alt_error_page_resource_fetcher.cc',
  'autofill_form.cc',
  'back_forward_list_client_impl.cc',
  'chrome_client_impl.cc',
  'chromium_bridge_impl.cc',
  'clipboard_conversion.cc',
  'context_menu_client_impl.cc',
  'cpp_binding_example.cc',
  'cpp_bound_class.cc',
  'cpp_variant.cc',
  'debugger_bridge.cc',
  'devtools/devtools_rpc.cc',
  'devtools/devtools_rpc.h',
  'devtools/devtools_rpc_js.h',
  'devtools/debugger_agent.h',
  'devtools/debugger_agent_impl.cc',
  'devtools/debugger_agent_impl.h',
  'devtools/debugger_agent_manager.cc',
  'devtools/debugger_agent_manager.h',
  'devtools/dom_agent.h',
  'devtools/dom_agent_impl.cc',
  'devtools/dom_agent_impl.h',
  'devtools/net_agent.h',
  'devtools/net_agent_impl.cc',
  'devtools/net_agent_impl.h',
  'devtools/tools_agent.h',
  'dom_operations.cc',
  'dom_serializer.cc',
  'dragclient_impl.cc',
  'editor_client_impl.cc',
  'entity_map.cc',
  'event_conversion.cc',
  'feed_preview.cc',
  'glue_util.cc',
  'glue_serialize.cc',
  'image_decoder.cc',
  'image_resource_fetcher.cc',
  'inspector_client_impl.cc',
  'localized_strings.cc',
  'media_player_private_impl.cc',
  'multipart_response_delegate.cc',
  'npruntime_util.cc',
  'password_autocomplete_listener.cc',
  'password_form_dom_manager.cc',
  'plugins/plugin_host.cc',
  'plugins/plugin_instance.cc',
  'plugins/plugin_lib.cc',
  'plugins/plugin_list.cc',
  'plugins/plugin_stream.cc',
  'plugins/plugin_stream_url.cc',
  'plugins/plugin_string_stream.cc',
  'resource_fetcher.cc',
  'resource_handle_impl.cc',
  'resource_loader_bridge.cc',
  'searchable_form_data.cc',
  'simple_webmimeregistry_impl.cc',
  'stacking_order_iterator.cc',
  'webclipboard_impl.cc',
  'webcursor.cc',
  'webdatasource_impl.cc',
  'webdevtoolsagent.h',
  'webdevtoolsagent_delegate.h',
  'webdevtoolsagent_impl.cc',
  'webdevtoolsagent_impl.h',
  'webdevtoolsclient.h',
  'webdevtoolsclient_delegate.h',
  'webdevtoolsclient_impl.cc',
  'webdevtoolsclient_impl.h',
  'weberror_impl.cc',
  'webframe_impl.cc',
  'webframeloaderclient_impl.cc',
  'webhistoryitem_impl.cc',
  'webkitclient_impl.cc',
  'webkit_glue.cc',
  'webmediaplayer_impl.cc',
  'webplugin_delegate.cc',
  'webplugin_impl.cc',
  'webtextinput_impl.cc',
  'weburlrequest_impl.cc',
  'webwidget_impl.cc',
  'webview_delegate.cc',
  'webview_impl.cc',
]

if env.Bit('windows'):
  # TODO(port): These extra files aren't win32-specific, they've just not been
  # tested on other platforms yet.
  input_files.extend([
    '$PENDING_DIR/AccessibleBase.cpp',
    '$PENDING_DIR/AccessibleDocument.cpp',
    'webaccessibilitymanager_impl.cc',
    'glue_accessibility_object.cc'
    'plugins/mozilla_extensions.cc',
    'plugins/webplugin_delegate_impl.cc',
    'webdropdata.cc',
  ])

if env.Bit('windows'):
  input_files.extend([
    'plugins/plugin_lib_win.cc',
    'plugins/plugin_list_win.cc',
    'plugins/plugin_stream_win.cc',
    'webcursor_win.cc',
    'webinputevent_win.cc',
    'webkit_glue_win.cc',
  ])
elif env.Bit('linux'):
  input_files.extend([
      'plugins/plugin_lib_linux.cc',
      'plugins/plugin_list_linux.cc',
      'plugins/webplugin_delegate_impl_gtk.cc',
      'webcursor_gtk.cc',
      'webinputevent_linux.cc',
      'webinputevent_util.cc',
      'webkit_glue_gtk.cc',
  ])
elif env.Bit('mac'):
  input_files.extend([
    'plugins/plugin_lib_mac.mm',
    'plugins/plugin_list_mac.mm',
    'webcursor_mac.mm',
  ])

if env.Bit('posix'):
  input_files.extend([
    'plugins/plugin_stream_posix.cc',
  ])

env.ChromeLibrary('glue', input_files)

env.ChromeMSVSProject('$WEBKIT_DIR/build/glue/glue.vcproj',
                name = 'Glue',
                dependencies = [
                       '$WEBKIT_DIR/build/WebCore/WebCore.vcproj',
                       '$WEBKIT_DIR/build/JSConfig/V8Config.vcproj',
                       ('$WEBKIT_DIR/build/V8Bindings/' +
                            'V8Bindings_prebuild.vcproj'),
                       ('$WEBKIT_DIR/build/localized_strings/' +
                            'localized_strings.vcproj'),
                ],
                guid='{C66B126D-0ECE-4CA2-B6DC-FA780AFBBF09}')
