# Copyright 2008, Google Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#    * Redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above
# copyright notice, this list of conditions and the following disclaimer
# in the documentation and/or other materials provided with the
# distribution.
#    * Neither the name of Google Inc. nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Import('env')

env = env.Clone()

env.Append(
  CCFLAGS = [
    '/TP',

    '/WX',

    '/wd4800',
    '/wd4503',
    '/wd4819',
  ],
)

input_files = [
    'alt_404_page_resource_fetcher.cc',
    'autocomplete_input_listener.cc',
    'plugins/webplugin_delegate_impl.cc',
    'plugins/plugin_string_stream.cc',
    'plugins/plugin_stream_url.cc',
    'plugins/plugin_stream.cc',
    'plugins/plugin_list.cc',
    'plugins/plugin_lib.cc',
    'plugins/plugin_instance.cc',
    'plugins/plugin_host.cc',
    'plugins/plugin_data_stream.cc',
    'plugins/mozilla_extensions.cc',
    'webwidget_impl.cc',
    'webview_impl.cc',
    'weburlrequest_impl.cc',
    'webtextinput_impl.cc',
    'webplugin_impl.cc',
    'webkit_glue.cc',
    'webinputevent.cc',
    'webhistoryitem_impl.cc',
    'webframeloaderclient_impl.cc',
    'webframe_impl.cc',
    'weberror_impl.cc',
    'webdropdata.cc',
    'webdocumentloader_impl.cc',
    'webdatasource_impl.cc',
    'webcursor.cc',
    'simple_clipboard_impl.cc',
    'searchable_form_data.cc',
    'resource_handle_win.cc',
    'resource_fetcher.cc',
    'password_form_dom_manager.cc',
    'password_autocomplete_listener.cc',
    'multipart_response_delegate.cc',
    'localized_strings.cc',
    'inspector_client_impl.cc',
    'glue_util.cc',
    'glue_serialize.cc',
    'feed_preview.cc',
    'image_resource_fetcher.cc',
    'image_decoder.cc',
    'event_conversion.cc',
    'editor_client_impl.cc',
    'entity_map.cc',
    'dragclient_impl.cc',
    'dom_operations.cc',
    'dom_serializer.cc',
    'debugger.cc',
    'cpp_variant.cc',
    'cpp_bound_class.cc',
    'cpp_binding_example.cc',
    'context_menu_client_impl.cc',
    'chrome_client_impl.cc',
    'cache_manager.cc',
    'alt_error_page_resource_fetcher.cc',
    '$PENDING_DIR/AccessibleBase.cpp',
    '$PENDING_DIR/AccessibleDocument.cpp',
]

env.StaticLibrary('Glue', input_files)


