# Copyright (c) 2006-2008 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

Import('env')

env = env.Clone()


env.Prepend(
    CPPPATH = [
        '$NPAPI_DIR',
        '$CHROME_DIR/tools/build/win',
        '$SKIA_DIR/include',
        '$SKIA_DIR/include/corecg',
        '$SKIA_DIR/platform',
        '#/..',
    ],
)

input_files = [
]

if env['PLATFORM'] == 'win32':
  env.Prepend(
      CCFLAGS = [
          '/TP',
      ],
  )

  # TODO(port)
  input_files.extend([
      'chrome_plugin_host.cc',
      'npobject_proxy.cc',
      'npobject_stub.cc',
      'npobject_util.cc',
      'plugin_channel.cc',
      'plugin_channel_base.cc',
      'plugin_main.cc',
      'plugin_process.cc',
      'plugin_thread.cc',
      'webplugin_delegate_stub.cc',
      'webplugin_proxy.cc',
  ])

env.ChromeStaticLibrary('plugin', input_files)

