# Copyright 2008, Google Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#    * Redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above
# copyright notice, this list of conditions and the following disclaimer
# in the documentation and/or other materials provided with the
# distribution.
#    * Neither the name of Google Inc. nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Import('env')

env = env.Clone()



env.Prepend(
    CPPPATH = [
        Dir("#/../third_party/npapi"),
        Dir("#/../chrome/tools/build/win"),
        Dir("#/../skia/include"),
        Dir("#/../skia/include/corecg"),
        Dir("#/../skia/platform"),
        Dir("#/.."),
    ],
    CPPDEFINES = [
        "CERT_CHAIN_PARA_HAS_EXTRA_FIELDS",
        "WIN32_LEAN_AND_MEAN",
    ],
    CCFLAGS = [
        '/TP',

        #'/Wp64',

        '/wd4503',
        '/wd4819',
    ],
)

input_files = [
  "npobject_proxy.cc",
  "webplugin_proxy.cc",
  "webplugin_delegate_stub.cc",
  "plugin_thread.cc",
  "plugin_process.cc",
  "plugin_main.cc",
  "plugin_channel_base.cc",
  "plugin_channel.cc",
  "chrome_plugin_host.cc",
  "npobject_util.cc",
  "npobject_stub.cc",
]

env.StaticLibrary('plugin', input_files)
