# Copyright (c) 2006-2008 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

Import('env', 'env_res')

env = env.Clone()
env_res = env_res.Clone()

env.SConscript([
    '$BZIP2_DIR/using_bzip2.scons',
    '$LIBXML_DIR/using_libxml.scons',
    '$CHROME_SRC_DIR/build/using_v8.scons',
], {'env':env})

if env.Bit('windows'):
  env_res.Append(
      CPPPATH = [
          '.',
          '$CHROME_SRC_DIR',
          '$NET_DIR',
      ],
      RCFLAGS = [
          ['/l', '0x409'],
      ],
  )

env.Append(
    CPPPATH = [
        '$BREAKPAD_DIR/src',
        '$WEBKIT_DIR/glue',
        '$GTEST_DIR/include',
    ],
    LIBS = [
        'test_shell',
        'glue',
        'port',
        'base',
        'base_gfx',
        'breakpad_handler',
        'googleurl',
        'net',
        'sdch',
        'skia',
        'gtest',
        'V8Bindings',
        'WebCore',
        'WTF',
        env['ICU_LIBS'],  # TODO(sgk):  '$ICU_LIBS' when scons is fixed
        'libjpeg',
        'libpng',
        'libxslt',
        'modp_b64',
        'zlib',
        'sqlite',
        'JavaScriptCore_pcre',
        'default_plugin',
    ],
)

if env.Bit('windows'):
  # TODO(port): put portable libs in above declaration.
  env.Append(
      LIBS = [
          'activex_shim',
          'breakpad_sender',
      ]
  )

if env.Bit('windows'):
  env.Append(
      LIBS = [
          'comctl32.lib',
          'rpcrt4.lib',
          'shlwapi.lib',
          'winmm.lib',
          'Urlmon',
      ],

      LINKFLAGS = [
          '/DELAYLOAD:"ws2_32.dll"',
          '/DELAYLOAD:"dwmapi.dll"',
          '/DELAYLOAD:"uxtheme.dll"',
          '/FIXED:No',
          '/SUBSYSTEM:CONSOLE',
          '/MACHINE:X86',
          '/safeseh',
          '/dynamicbase',
          '/ignore:4199',
          '/nxcompat',
      ],
  )
elif env.Bit('posix'):
  env.Append(
      LIBS = [
          'event',
      ]
  )

if env.Bit('mac'):
  env.Append(
      CPPPATH = [
          '$THIRD_PARTY_DIR/WebKit/WebKit/mac/WebCoreSupport',
      ],
  )

input_files = [
    'event_sending_controller.cc',
    'layout_test_controller.cc',
    'simple_resource_loader_bridge.cc',
    'test_navigation_controller.cc',
    'test_shell_request_context.cc',
    'test_shell_switches.cc',
    'test_shell.cc',
    'test_webview_delegate.cc',
    'text_input_controller.cc',
]
if env.Bit('windows'):
  # TODO(port): Consider porting drag_delegate.cc and drop_delecate.cc.
  input_files.extend([
      'drag_delegate.cc',
      'drop_delegate.cc',
      'test_shell_win.cc',
      'test_webview_delegate_win.cc',
      'webview_host_win.cc',
      'webwidget_host_win.cc',
  ])
elif env.Bit('linux'):
  input_files.extend([
      'webview_host_gtk.cc',
      'webwidget_host_gtk.cc',
      'test_shell_gtk.cc',
      'test_webview_delegate_gtk.cc',
  ])

lib = env.ChromeStaticLibrary('test_shell', input_files)

resources = []
exe_input_files = [
  'test_shell_main.cc',
]

if env.Bit('windows'):
  # TODO(port): figure out what to do with resources.
  resources = [
      env_res.RES('resources/test_shell.rc'),
      '$NET_DIR/net_resources.res',
      '$TARGET_ROOT/grit_derived_sources/webkit_strings_en-US.res',
  ]

  exe_input_files += [
      '$V8_DIR/snapshot-empty$OBJSUFFIX'
  ]

test_shell = env.ChromeProgram('test_shell', resources + exe_input_files)

i = env.Install('$TARGET_ROOT', test_shell)
env.Alias('webkit', i)

if env.Bit('windows'):
  env.Depends(test_shell, '$V8_DIR/vc80.pdb')

test_files = [
    'image_decoder_unittest.cc',
    'keyboard_unittest.cc',
    'layout_test_controller_unittest.cc',
    'node_leak_test.cc',
    'run_all_tests.cc',
    'test_shell_test.cc',
    'text_input_controller_unittest.cc',
    '$WEBKIT_DIR/glue/bookmarklet_unittest.cc',
    '$WEBKIT_DIR/glue/context_menu_unittest.cc',
    '$WEBKIT_DIR/glue/cpp_bound_class_unittest.cc',
    '$WEBKIT_DIR/glue/cpp_variant_unittest.cc',
    '$WEBKIT_DIR/glue/dom_operations_unittest.cc',
    '$WEBKIT_DIR/glue/dom_serializer_unittest.cc',
    '$WEBKIT_DIR/glue/glue_serialize_unittest.cc',
    '$WEBKIT_DIR/glue/iframe_redirect_unittest.cc',
    '$WEBKIT_DIR/glue/mimetype_unittest.cc',
    '$WEBKIT_DIR/glue/multipart_response_delegate_unittest.cc',
    '$WEBKIT_DIR/glue/password_autocomplete_listener_unittest.cc',
    '$WEBKIT_DIR/glue/regular_expression_unittest.cc',
    '$WEBKIT_DIR/glue/resource_fetcher_unittest.cc',
    '$WEBKIT_DIR/glue/webframe_unittest.cc',
    '$WEBKIT_DIR/tools/webcore_unit_tests/GKURL_unittest.cpp',
    '$WEBKIT_DIR/tools/webcore_unit_tests/BMPImageDecoder_unittest.cpp',
    '$WEBKIT_DIR/tools/webcore_unit_tests/ICOImageDecoder_unittest.cpp',
    '$WEBKIT_DIR/tools/webcore_unit_tests/XBMImageDecoder_unittest.cpp',
    '$V8_DIR/snapshot-empty$OBJSUFFIX',
]

if env.Bit('windows'):
  # TODO(port): put portable files in above test_files declaration.
  test_files.extend([
      'plugin_tests.cc',
      # Commented out until a regression is fixed and this file is restored.
      #'$WEBKIT_DIR/glue/stringimpl_unittest.cc',
      '$WEBKIT_DIR/glue/webplugin_impl_unittest.cc',
      '$WEBKIT_DIR/tools/webcore_unit_tests/UniscribeHelper_unittest.cpp',
  ])

test_shell_tests = env.ChromeTestProgram('test_shell_tests',
                                         resources + test_files)
i = env.Install('$TARGET_ROOT', test_shell_tests)
env.Alias('webkit', i)
