# Copyright (c) 2006-2008 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

Import('env_test')

env_test = env_test.Clone()

env_test.Prepend(
    CPPDEFINES = [
        'PNG_USER_CONFIG',
        'CHROME_PNG_WRITE_SUPPORT',
        '_DEBUG',
    ],
    CPPPATH = [
        '$ZLIB_DIR',
        '$LIBPNG_DIR',
        '#/..',
    ],
    LIBS = [
        'skia',
        'libpng',
        'base_gfx',
        'icuuc',
        'zlib',
        'base',
    ],
)

env_test.Prepend(
    LINKFLAGS = [
        '/INCREMENTAL',
        '/DEBUG',

        '/DELAYLOAD:"dwmapi.dll"',
        '/DELAYLOAD:"uxtheme.dll"',

        '/SUBSYSTEM:CONSOLE',

        '/MACHINE:X86',
        '/FIXED:No',

        '/safeseh',
        '/dynamicbase',
        '/ignore:4199',
        '/nxcompat',
    ],
)

input_files = [
    'image_diff.cc',
]

exe = env_test.ChromeTestProgram('image_diff', input_files)
i = env_test.Install('$TARGET_ROOT', exe)

env_test.Alias('chrome', i)

