# Copyright (c) 2006-2008 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

Import('env')

env = env.Clone()

env.Prepend(
    CPPPATH = [
        '#/../webkit/glue',
        '$ICU38/public/common',
        '$ICU38/public/i18n',
        '#/../third_party/libxml/include',
        '#/../third_party/npapi',
        '#/..',
    ],
)

env.Append(
    CPPDEFINES = [
        'U_STATIC_IMPLEMENTATION',
        'LIBXML_STATIC',
    ],
    CCFLAGS = [
        '/TP',

        '/WX',
        '/Wp64',
    ],
)

input_files = [
    'activex_installer.cc',
    'default_plugin.cc',
    'plugin_main.cc',
    'plugin_impl.cc',
    'plugin_database_handler.cc',
    'plugin_install_job_monitor.cc',
    'install_dialog.cc',
]

env.ChromeStaticLibrary('default_plugin', input_files)

