# Copyright (c) 2006-2008 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

Import('env')

env = env.Clone()

env.Prepend(
    CPPPATH = [
        '$BREAKPAD_DIR/src',
        '#/..',
    ],
    LIBS = [
        'base',
        'base_gfx',
        'breakpad_handler',
        'breakpad_sender',
        'common',
        env['ICU_LIBS'],  # TODO(sgk):  '$ICU_LIBS' when scons is fixed
        'skia',
        'zlib',
    ],
)

env.Prepend(
    LINKFLAGS = [
        '/INCREMENTAL',

        '/DELAYLOAD:"dwmapi.dll"',
        '/DELAYLOAD:"uxtheme.dll"',

        '/DEBUG',
        '/MACHINE:X86',
        '/FIXED:No',

        '/safeseh',
        '/dynamicbase',
        '/ignore:4199',
        '/nxcompat',

    ],
)

input_files = [
    'main.cc',
    'crash_service.cc',
]

exe = env.ChromeProgram('crash_service', input_files)

i = env.Install('$TARGET_ROOT', exe)
Alias('chrome', i)

