# Copyright (c) 2006-2008 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

Import('env_test')


env_test = env_test.Clone()


env_test.Prepend(
    CPPDEFINES = [
        'UNIT_TEST',
    ],
    CPPPATH = [
        '$GTEST_DIR/include',
        '$GTEST_DIR',
        '#/..',
    ],
    LIBS = [
        'util',
        'gtest',
        env_test['ICU_LIBS'],  # TODO(sgk):  '$ICU_LIBS' when scons is fixed
        'base',
    ],
)

env_test.Prepend(
    LINKFLAGS = [
        '/INCREMENTAL',
        '/DEBUG',

        '/DELAYLOAD:"dwmapi.dll"',
        '/DELAYLOAD:"uxtheme.dll"',

        '/MACHINE:X86',
        '/FIXED:No',

        '/safeseh',
        '/dynamicbase',
        '/ignore:4199',
        '/nxcompat',
    ],
    LIBS = [
        'comsupp.lib',
        'oleacc.lib',
        'rpcrt4.lib',
        'shlwapi.lib',
    ],
)

input_files = [
    '$CHROME_DIR/installer/setup/setup_constants$OBJSUFFIX',
    '$CHROME_DIR/installer/util/run_all_unittests$OBJSUFFIX',
    'chrome_mini_installer.cc',
    'mini_installer_test_constants.cc',
    'test.cc',
]

exe = env_test.ChromeTestProgram('mini_installer_test', input_files)
i = env_test.Install('$TARGET_ROOT', exe)

env_test.Alias('chrome', i)

